version: 2.1

jobs:
  docker-compose-up:
    docker:
      - image: cimg/base:current  # This is the Docker image your job will run in, based on Ubuntu, with basic build tools.
    steps:
      - checkout

      - setup_remote_docker # This is there because cicrcleCi containers can’t run Docker natively because they’re already running inside Docker.
                            # This step sets up a separate remote Docker environment here Docker commands can work.
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Run Docker Compose
          command: docker-compose up -d

workflows:
  run-compose:
    jobs:
      - docker-compose-up
