version: 2.1

jobs:
  docker-compose-up:
    docker:
      - image: cimg/openjdk:17.0 
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Run Docker Compose
          command: docker-compose up -d

      - run:
          name: Install SonarScanner CLI
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner.zip
            mv sonar-scanner-* sonar-scanner
            echo 'export PATH="$PWD/sonar-scanner/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Run SonarCloud Analysis
          command: |
            source $BASH_ENV
            sonar-scanner \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  run-compose:
    jobs:
      - docker-compose-up
