version: 2.1

jobs:
  docker-compose-up:
    machine: true
    resource_class: sahilrajputwins/my-hosted-agent
    steps:
      - checkout
      
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Run Docker Compose
          command: docker-compose up -d

workflows:
  run-compose:
    jobs:
      - docker-compose-up
